# Basic Site Settings
locale                   : "en-US"
title                    : "Zijing Wan's Personal Homepage"
title_separator          : "-"
name                     : &name "Zijing Wan"
description              : &description "Senior Student from UCSB"
url                      : https://ZijingWan.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  :  # 如果项目在子目录中，这里应设置为子目录名，例如 "/projects"
repository               : "ZijingWan/ZijingWan.github.io"

# Site Author - The following control what appear as part of the author content on the side bar.
author:
  avatar           : "WZJ.png"
  name             : "Zijing Wan"
  pronouns         : "University of California, Santa Barbara"
  bio              : |
  location         : "Santa Barbara"
  email            : "zijing_wan@ucsb.edu"

# Publication Category
publication_category:
  books:
    title: 'Books'
  manuscripts:
    title: 'Journal Articles'    
  conferences:
    title: 'Conference Papers'

# Site Settings
teaser                   :  
breadcrumbs              : false
words_per_minute         : 160
future                   : true
read_more                : "disabled"
comments:
  provider               : 
atom_feed:
  hide                   : false
  path                   : 

# SEO Related
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

# Social Sharing
twitter:
  username               : &twitter
facebook:
  username               :
  app_id                 :
og_image                 :  

# Analytics
analytics:
  provider               : "false"

# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - .jekyll-assets-cache
  - node_modules
  - tmp
keep_files:
  - .git

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  auto_ids: true

# These settings control the types of collections used by the template
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  projects:  # 更新此处为 projects
    output: true
    permalink: /projects/:path/
  talks:
    output: true
    permalink: /:collection/:path/

# These settings control how pages and collections are included in the site
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _teaching
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _publications
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _projects  # 更新此处为 projects
  - scope:
      path: ""
      type: projects
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _talks
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone: Etc/UTC

# Plugins
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development
